basePath: /api/v1
definitions:
  dto.RegisterRequest:
    properties:
      account_type:
        enum:
        - savings
        - checking
        - deposit
        type: string
      nama:
        type: string
      nik:
        type: string
      no_hp:
        type: string
    required:
    - account_type
    - nama
    - nik
    - no_hp
    type: object
  dto.RegisterResponse:
    properties:
      no_rekening:
        type: string
      remark:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Test for managing accounts & transactions service.
  title: Go Backend Test
  version: "1.0"
paths:
  /daftar:
    post:
      consumes:
      - application/json
      description: Mendaftarkan nasabah baru dengan nama, NIK, no_hp, dan tipe akun
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
      summary: Register new nasabah
      tags:
      - accounts
swagger: "2.0"
